### ISSUE TITLE
add github actions support

### ISSUE THREAD

**Issue by santoshndev** [sarathp06/moodle-block_site_announcements#1]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project 
eg:
https://github.com/santoshndev/moodle-block_site_stats/blob/main/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by sarathp06** [comment]
Hi @santoshndev 
Thank you for the guidance on setting up the GitHub workflow for the Moodle plugin. I have successfully uploaded the ci.yml file to the .github/workflows directory

**Comment by sarathp06** [comment]
Hi @santoshndev
Thank you for the guidance on setting up the GitHub workflow for the Moodle plugin. I have successfully uploaded the ci.yml file to the .github/workflows directory
